name = "mydiary-api"
main = "src/index.js"
compatibility_date = "2024-01-01"

[vars]
JWT_SECRET = "change-me-in-dashboard-use-32-chars-minimum"

# ====== 生产环境（默认） ======
[[d1_databases]]
binding = "DB"
database_name = "mydiary-db"
database_id = "ed7e7954-5f55-439c-a76a-228f1124512b"

# Workers AI（embedding + LLM 问答）
[ai]
binding = "AI"

# 验证码 KV（5 分钟 TTL 在代码里写）
[[kv_namespaces]]
binding = "verify_codes"
id = "81191d85345e4bde9a9895c530a24d9a"

# ====== 测试环境 ======
[env.dev]
name = "mydiary-api-dev"
[env.dev.vars]
JWT_SECRET = "dev-secret-change-me-please-32chars!"

[[env.dev.d1_databases]]
binding = "DB"
database_name = "mydiary-db-dev"
database_id = "fb45cce8-c051-4f20-a560-ea2dc3cadb26"

# Workers AI dev
[env.dev.ai]
binding = "AI"

[[env.dev.kv_namespaces]]
binding = "verify_codes_dev"
id = "4b8fe160e0044927b62f029d95535c65"
